### ISSUE TITLE
Sensor centro_notifiche not exist.

### ISSUE THREAD

**Issue by matteos1** [caiosweet/Package-Notification-HUB-AppDaemon#11]
sensor.centro_notifiche not exist

**Comment by caiosweet** [comment]
No, it will be created by Notifier app. Please wait for the release of the new version, for both, App and package.

**Comment by matteos1** [comment]
now is ready to uplad in HA? thank you

**Comment by caiosweet** [comment]
> now is ready to uplad in HA? thank you

Not yet. 
I suggest you 
switch from _`watching`_ to **`Release only`** on github notifications. :0)
