### ISSUE TITLE
secrets.yaml

### ISSUE THREAD

**Issue by matteos1** [caiosweet/Package-Notification-HUB-AppDaemon#15]
_#----------------------------------------------------------------------------------------------------#
# SECTION 3 - In questa sezione ci sono altre entità lette da Home Assistant per Extra Feautures 
#----------------------------------------------------------------------------------------------------#

# Group (group.media_player_alexa)_

in secrets. yaml the sintiax is:

media_player_alexa: [
  "media_player.echo_dot_di_matteo",
]

or 

media_player_alexa: [
  - media_player.echo_dot_di_matteo

the error  **Alexa Manager - Warker Error** what means?

**Comment by caiosweet** [comment]
Maybe you overwrote the secret file?  Check the secret.

**Comment by legolas0802** [comment]
Errore mio non ho fatto caso che citavi la sezione 3. Se non ricordo male nel secondo caso non ci vanno le parentesi quadre, in ogni caso me hai inserita solo una

**Comment by caiosweet** [comment]
Ricordo sempre, che i dati del secret fanno riferimento ai file del package... se non si usa il file extra.yaml, la sez 3 la puoi omettere.
Se invece usi anche il file extra.yaml, allora ci devi mettere le tue entità per il gruppo. 
Chiaro, che se non hai Google, devi cancellare il gruppo dal file extra.yaml, o altrimenti, lasciare tutto come sta e mettere due quadre nel secrets, così facendo si creare un gruppo vuoto.

`media_player_google: []`
