### ISSUE TITLE
Error in secret

### ISSUE THREAD

**Issue by jokerigno** [caiosweet/Package-Notification-HUB-AppDaemon#16]
Ciao Caio,

solo una nota: nella wiki dici che se non uso alexa posso eliminare il file e la sezione nel secret.

> Input Select Alexa Media Player
> Media Player Alexa to use as Default. Enter your 'media_player' and/or 'group' and/or Sensor devices with friandly_name. NB: If you do not have Alexa devices, you can delete the file hub_alexa.yaml and the code below.
> 
> # (Ref. input_select.notification_media_player_alexa)
> notification_media_player_alexa_hub: 
>   - Sala
>   - Studio
>   - Echo Dot di Caio
>   - Gruppo Alexa
>   - Last Alexa

In realtà posso solo eliminare l'hub alexa.

Se tolgo "notification_media_player_alexa_hub" mi da errore.

**Comment by caiosweet** [comment]
Ciao, errore di configurazione o in appDaemon?

Strano, perché il riferimento a questo dato è in quel file.
Provato a fare più check?
Forse va riavviato e poi cancellata la parte del secret?
Non è che hai un richiamo in un altro file tuo personale?

Il mio scopo è quello di prendere lo stretto necessario e di semplificare la configurazione, hai idee in merito?

Se riesco, il prima possibile vorrei provare una installazione da zero di questo complesso package/app e vedere cosa semplificare.

Decidere cosa lasciare come definitivo nel package e cosa prendere autonomamente da un altra cartella (vedi automazioni, file extra.yaml etc)

Ad esempio, vorrei non più usare i device tracker, ma solo il Person. Toglierlo dal secret e  generare il gruppo in automatico all'avvio.
Tu che ne pensi?

Qualsiasi suggerimento è ben accetto.

**Comment by jokerigno** [comment]
Uhm. L'ho rifatto stamattina ed effettivamente sono riuscito a toglierlo (l'errore era in config). Magari facendolo con qualche ora di sonno è stato d'aiuto!

 Ho però un problema con l'automazione Auto Volume Hub. Te lo riporto qui ma se preferisci posso aprire una issue ad hoc.

In pratica sto facendo pulizia da alexa dato che non ce l'ho in casa così ho commentato alcune parti:

```
  - alias: Auto Volume Hub
    mode: queued
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.period_of_day_volume
      - platform: homeassistant
        event: start
    action:
      - variables:
       #   group_alexa: "{{state_attr('group.media_player_alexa', 'entity_id')|join(', ')}}"
          group_google: "{{state_attr('group.media_player_google', 'entity_id')|join(', ')}}"
       #   list_alexa: "{{ group_alexa if states.input_boolean.alexa_switch else 'none'}}" # return string!!
          list_google: "{{group_google if states.input_boolean.google_switch else 'none'}}"
          all_entity: "{{(list_alexa, list_google)|reject('sameas','none')|join(', ')}}"
          volume: "{{states('sensor.period_of_day_volume')|float}}"
      # - choose:
          # - conditions: "{{list_alexa is not none}}"
            # sequence:
              # - service: notify.alexa_media
                # data:
                  # data:
                    # type: tts
                  # target: "{{list_alexa}}"
                  # message: >
                    # <speak>
                    # <break time="4s"/>
                    # <prosody volume="silent">volume</prosody>
                    # </speak>
              # - delay: "00:00:02"
      # - choose:
          # - conditions: "{{list_alexa is not none or list_google is not none}}"
            # sequence:
              # - service: media_player.volume_set
                # data:
                  # entity_id: >
                    # {{all_entity}}
                  # volume_level: "{{(volume|round(2))/100}}"
              # - service: input_number.set_value
                # data:
                  # entity_id:
                    # - input_number.intercom_message_volume
                    # - input_number.default_restore_volume
                  # value: "{{volume}}"
      # - conditions: "{{list_alexa is not none or list_google is not none}}"
        # sequence:
      - service: media_player.volume_set
        data:
          entity_id: >
            {{all_entity}}
          volume_level: "{{(volume|round(2))/100}}"
      - service: input_number.set_value
        data:
          entity_id:
            - input_number.intercom_message_volume
            - input_number.default_restore_volume
          value:  #"{{volume}}"
```
Solo che nel log di HA vedo un errore:

`Auto Volume Hub: Error executing script. Invalid data for call_service at pos 2: not a valid value for dictionary value @ data['entity_id']`

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 426, in async_trigger
    await self.action_script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1010, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 710, in async_run
    await super().async_run()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 245, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1402, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 340, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 336, in _exec
    v = func(v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 215, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 340, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 338, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: not a valid value for dictionary value @ data['entity_id']
```
eppureil sensore esiste! Forse ho commentato male?

PS: Sarei felicissimo di condividere i miei pensieri con te-voi. Li butto qui un po' alla rinfusa ma magari poi ci spostiamo sul forum.

- Eliminerei il secret ad hoc e riporterei le info che servono nel secret "generale" un po' come avviene per gli altri packages, uno su tutti natural events.
- Si userei il person perchè più completo e sarebbe figo se si generasse all'avvio. 
- Migliorerei qua e la la wiki sia per alcuni typo sia per migliorare al massimo la chiarezza. Tipo ho visto together scritto male a volte, così come friendly_name. Sono piccolezze ma magari aiutano. 
- Mi prometto di condividere con voi il mio automation_hub un po' come ha fatto Angelo. Questo package ha un potenziale INFINITO ed è a mio avviso una delle cose più BELLE che HA permette.

**Comment by caiosweet** [comment]
Ciao, se trovi altre errori o vuoi collaborare, sentiti libero di scrivere, anche sul forum o un messaggio privato sul forum, non sono molto ferrato con l'inglese :0)

Per il secret globale, si era evitato proprio perchè c'erano troppe cose da aggiungere a quelle già presenti :D e perchè nelle versioni precedenti di appdaemon c'erano problemi (ora non più). Vediamo che ne pensano gli altri.
Tieni presente, che il problema era passare i servizi Google e Voip ad appDaemon insieme a quelli del package in un unico posto.


Se usi solo Google, l'automazione dovrebbe essere più o meno così: (non testata)
```
  # Google
  - alias: Auto Volume Hub
    mode: queued
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.period_of_day_volume
      - platform: homeassistant
        event: start
    action:
      - variables:
          volume: "{{states('sensor.period_of_day_volume')|float}}"
      - service: media_player.volume_set
        data:
          entity_id: all
          volume_level: "{{(volume|round(2))/100}}"
      - service: input_number.set_value
        data:
          entity_id:
            - input_number.intercom_message_volume
            - input_number.default_restore_volume
          value: "{{volume}}"
```
