### ISSUE TITLE
If the device name google contains spaces it is not resolved as entity_id.

### ISSUE THREAD

**Issue by jokerigno** [caiosweet/Package-Notification-HUB-AppDaemon#17]
Ciao,

sono sempre io. 

Nuovo errore sempre relativo al secret:

Questa è sezione dove elenco i miei google mini sparsi per la casa:

```
notification_media_player_google_hub:
  # - Google Home Mini
  - Corridoio
  - Broadcast
  # - Casa Concordia
  - Gminis
```

Come vedi ce ne sono due commentati. Questo perchè se uno di loro è dentro il gruppo ricevo un errore e le notifiche con script.my_notify non partono (l'interfono invece funziona!).

Ecco l'errore:

> Dettagli registro (ERROR)
> Logger: aiohttp.server
> Source: core.py:865
> First occurred: 16:38:25 (2 occurrences)
> Last logged: 16:38:25
> 
> Error handling request
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
>     resp = await task
>   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
>     resp = await handler(request)
>   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
>     result = await result
>   File "/usr/src/homeassistant/homeassistant/components/api/__init__.py", line 274, in post
>     hass.states.async_set(
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1183, in async_set
>     state = State(
>   File "/usr/src/homeassistant/homeassistant/core.py", line 865, in __init__
>     raise InvalidEntityFormatError(
> homeassistant.exceptions.InvalidEntityFormatError: Invalid entity id encountered: media_player.google home mini. Format should be <domain>.<object_id>

Ho controllato l'integrazione e i nomi dei devices sono

media_player.casa_concordia ------ friedly name: Casa Concordia
media_player.google_home_mini ------ friedly name: Google Home Mini

**Comment by caiosweet** [comment]
Ciao.
Veramente il primo non c'è mai stato di errore :D

Vedo `media_player.google home mini` senza underscore... da dove proviene questo errore?
hai usato in una automazione l'opzione media player? Non è che hai scritto:
`media_player: media_player.google home mini` ?

Come posso replicare l'errore?
Hai provato a scrivere nel secrets il nome tra apici?
`- "google home mini" `

**Comment by legolas0802** [comment]
> Ciao,
> 
> sono sempre io.
> 
> Nuovo errore sempre relativo al secret:
> 
> Questa è sezione dove elenco i miei google mini sparsi per la casa:
> 
> ```
> notification_media_player_google_hub:
>   # - Google Home Mini
>   - Corridoio
>   - Broadcast
>   # - Casa Concordia
>   - Gminis
> ```
> 
> Come vedi ce ne sono due commentati. Questo perchè se uno di loro è dentro il gruppo ricevo un errore e le notifiche con script.my_notify non partono (l'interfono invece funziona!).
> 
> Ecco l'errore:
> 
> > Dettagli registro (ERROR)
> > Logger: aiohttp.server
> > Source: core.py:865
> > First occurred: 16:38:25 (2 occurrences)
> > Last logged: 16:38:25
> > Error handling request
> > Traceback (most recent call last):
> > File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
> > resp = await task
> > File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
> > resp = await handler(request)
> > File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
> > return await handler(request)
> > File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
> > return await handler(request)
> > File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
> > return await handler(request)
> > File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
> > return await handler(request)
> > File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
> > result = await result
> > File "/usr/src/homeassistant/homeassistant/components/api/**init**.py", line 274, in post
> > hass.states.async_set(
> > File "/usr/src/homeassistant/homeassistant/core.py", line 1183, in async_set
> > state = State(
> > File "/usr/src/homeassistant/homeassistant/core.py", line 865, in **init**
> > raise InvalidEntityFormatError(
> > homeassistant.exceptions.InvalidEntityFormatError: Invalid entity id encountered: media_player.google home mini. Format should be .<object_id>
> 
> Ho controllato l'integrazione e i nomi dei devices sono
> 
> media_player.casa_concordia ------ friedly name: Casa Concordia
> media_player.google_home_mini ------ friedly name: Google Home Mini

Nella parte finale dell'errore vedo media_player.google home mini , senza gli underscore. Non è che hai sbagliato a scrivere in qualche automazione o da qualche altra parte?

**Comment by caiosweet** [comment]
Abbiamo trovato l'errore, credo che Gianpi lo correggerà in un attimo.

**Comment by jokerigno** [comment]
Almeno questa volta l'errore esiste!

**Comment by caiosweet** [comment]
Si, ma non dipendeva dal secrets😎 
[issue #26](https://github.com/jumping2000/notifier/issues/26)

Volendo, se Gianpi non ha tempo ho messo al volo una patch nel file Google manager in beta nel mio fork Notifier 
Ma, consiglio di aspettare nuova versione del Notifier😇  
È una questione di conversione da name ad entity, e data l'ora, non ho fatto la conversione, ma solo un replace. Mentre va proprio cercato il valore entity_id di quel nome👍

**Comment by jokerigno** [comment]
Ok allora aspetto. E provo a trovare nuovi errori ahahahahah (scherzo eh!)

**Comment by caiosweet** [comment]
Bene. Chiudo, dipende tutto dal Notifier Google manager 😎
[fixed notifier 2.0.3](https://github.com/jumping2000/notifier/releases/tag/2.0.3)
