### ISSUE TITLE
Cloud TTS service is wrong in wiki

### ISSUE THREAD

**Issue by jokerigno** [caiosweet/Package-Notification-HUB-AppDaemon#19]
Nella wiki c'è scritto che per aggiungere il TTS cloud di Google bisogna aggiungere 

> "tts_google_cloud: google_cloud"

In realtà il nome completo del servizio è diverso quindi con me funziona 

> "tts_google_cloud: google_cloud_say"

Ciao !

**Comment by caiosweet** [comment]
Il nome del servizio dipende da te, ma ok, ci sta mettere nel wiki quello di default.
Grazie per averlo modificato. chiudo.
