### ISSUE TITLE
Alexa Manager - Worker Error 

### ISSUE THREAD

**Issue by matteos1** [caiosweet/Package-Notification-HUB-AppDaemon#21]
in frontend till some days, there is this error:
Alexa Manager - Worker Error 
there are some solution?
and alexa not work..
![image](https://user-images.githubusercontent.com/16237822/111758496-e13bcb00-889c-11eb-88a6-20cfd23ab2a6.png)
Alexa_Manager: Querying a specific attribute is only possible for a single entity

**Comment by caiosweet** [comment]
A notifier update should come out ... in the meantime, if you want, you can replace the `/config/appdaemon/apps/notifier/alexa_manager.py` file with [this](https://github.com/caiosweet/notifier/blob/beta/apps/notifier/alexa_manager.py).

Restart appDaemon and let me know how it goes.

**Comment by matteos1** [comment]
i think it work. thank you @caiosweet
