### ISSUE TITLE
riproduzione interfono - send duplicate messages

### ISSUE THREAD

**Issue by riddik14** [caiosweet/Package-Notification-HUB-AppDaemon#44]
riproduzione interfono
scrivo il messaggio
invio ma viene riprodotto 3 volte.
come mai?

**Comment by caiosweet** [comment]
Ciao. 
Scrivi il messaggio e premi invio (da tastiera) o il pulsante last Message? 
Riproduce 3 volte con Alexa o google?
Usi il gruppo per la riproduzione?
Se niente di tutto ciò, riavviato appdaemon dopo aggiornamento?

**Comment by riddik14** [comment]
Sì appdaemon riavviato, se invio nuovo messaggio a singolo Google o singolo alexa viene riprodotto tre volte e anche sulle notifiche di homeassistant trovo tre coltre il msg . 

{
  "alexa_group_player": [
    "group.ovunque"
  ],
  "alexa_media_player": [
    "media_player.echo",
    "media_player.nexxt",
    "media_player.firetvstick_di_domenico",
    "media_player.ovunque"
  ],
  "alexa_options": [
    "Echo",
    "Nexxt",
    "FireTVStick di Domenico",
    "Ovunque",
    "All Echo devices"
  ],
  "alexa_select": "Echo",
  "alexa_sensor": "media_player.echo",
  "alexa_skill_id": "",
  "beta_version": false,
  "day_period": "Mattina",
  "day_period_volume": 50,
  "debug": true,
  "dnd": "off",
  "download": false,
  "enabled_auto_volume": true,
  "enabled_home_assistant_event": true,
  "exclude_media_player": [],
  "google_group_player": [
    "group.google_home_all"
  ],
  "google_media_player": [
    "media_player.camera_da_letto",
    "media_player.cameretta",
    "media_player.cucina",
    "media_player.soggiorno",
    "media_player.giorno",
    "media_player.notte",
    "media_player.tutti"
  ],
  "google_options": [
    "Camera da letto",
    "Cameretta",
    "Cucina",
    "Soggiorno",
    "giorno",
    "notte",
    "tutti",
    "All Google Home"
  ],
  "google_select": "tutti",
  "google_sensor": "media_player.tutti",
  "ha_event_notify": [],
  "is_script": true,
  "location_tracker": "home",
  "notify_options": [
    "Persistent Notification",
    "Telegram",
    "Telegram2",
    "Telegram Call",
    "Pushover",
    "Pushbullet",
    "Notify",
    "Whatsapp Mio"
  ],
  "notify_select": "Whatsapp Mio",
  "notify_sensor": "notify.whatsapp_mio",
  "notify_service_list": [
    "notify.persistent_notification",
    "telegram",
    "telegram2",
    "telegram_call",
    "Pushover",
    "Pushbullet",
    "notify",
    "whatsapp_mio"
  ],
  "packages_folder": "/config/packages",
  "people_home": "on",
  "person": [
    "person.papaa",
    "person.mamma"
  ],
  "personal_assistant": "Jarvis",
  "reverso_tts": "reversotts_say",
  "sip_server_name": "fritz.box:5060",
  "time_pattern_hours": 3,
  "tts_google": "google_translate_say",
  "tts_google_cloud": "google_cloud"
}
![Uploading IMG_8298.png…]()

**Comment by riddik14** [comment]
![IMG_8299](https://github.com/caiosweet/Package-Notification-HUB-AppDaemon/assets/37450907/d87be37d-1039-49c3-b59e-af3965d4eac0)

**Comment by riddik14** [comment]
![IMG_8298](https://github.com/caiosweet/Package-Notification-HUB-AppDaemon/assets/37450907/ca43c838-a6eb-4b85-af26-af60d19c00f0)

**Comment by riddik14** [comment]
Come vedi anche i cambi di volume avvengono per tre volte. L’ultima notifica invece usa automazione diretta con tts senza passare dal centro notifiche

**Comment by riddik14** [comment]
Ho riscaricato notifier. Arrivano comunque 3. Vocalmente si alternano Google ed alexa per tre volte con lo stesso messaggio

**Comment by riddik14** [comment]
Ops ho debug attivo. Potrebbe dipendere da questo?

**Comment by caiosweet** [comment]
> "exclude_media_player": [],

intanto, come consiglio, inserirei i gruppi dei media player nella lista da escludere, altrimenti aggiorna gli stessi media player. Lo puoi fare editando la stessa automazione creata dalla blueprint.
PS escluderei anche dalla lista dei media player Alexa, quelle entità che forse non funzionano con home assistant (tipo `media_player.ovunque`, `media_player.this_device`...)

Per i tre messaggi, è strano. L'unica cosa che mi viene in mente, non è che hai più automazioni fatte con la blueprint? Controlla se non hai altre automaziono tipo 
`automation.centro_notifiche_configurazione_avvio`
`automation.centro_notifiche_configurazione_avvio_2`
`automation.centro_notifiche_configurazione_avvio_3`

La cosa che mi fa pensare che hai più automazioni, è aver visto che le notizie ansa (quindi fuori dalla automazione creata dalla blueprint) è unica. Mentre, interfono (per lo più utile per test) e auto-volume, si duplicano/triplicano.

> Ops ho debug attivo. Potrebbe dipendere da questo?

No, non credo. Però è stato utile per vedere la configurazione... che mentre leggo, cerco di capire perchè hai 3 notifiche :)

**Comment by riddik14** [comment]
Ho provato con service a mandarne una e arriva una. Solo la funzione interfono ne manda 3.
Invio con centro raccolta_hp e ne arriva 1. Quindi ritorno che solo interfono ne manda tre. Il resto che usa script.my_notify funziona bene

**Comment by riddik14** [comment]
![Uploading IMG_8300.png…]()

**Comment by caiosweet** [comment]
Ho aggiornato il messaggio precedente...
Altra cosa, controlla che non ci siano altre automazioni  che erano incluse nel vecchio package...

**Comment by riddik14** [comment]
Il vecchio pk l’ho eliminato e salvato solo hub_build_message

**Comment by riddik14** [comment]
![IMG_8300](https://github.com/caiosweet/Package-Notification-HUB-AppDaemon/assets/37450907/a2d200dc-5ccf-4393-ab5b-f4592383c13d)

**Comment by caiosweet** [comment]
hai riletto il messaggio [precedente](https://github.com/caiosweet/Package-Notification-HUB-AppDaemon/issues/44#issuecomment-1627643237)

Controlla se hai duplicati dell'automazione blueprint.

**Comment by riddik14** [comment]
![IMG_8302](https://github.com/caiosweet/Package-Notification-HUB-AppDaemon/assets/37450907/274bfdb8-cfcd-4219-a654-6e35da744a45)
![IMG_8301](https://github.com/caiosweet/Package-Notification-HUB-AppDaemon/assets/37450907/9a54a58b-5500-4e3e-be1a-877b626be302)


Ultimo invio fatto con le impostazione allegate. Non penso che altre automazioni interferiscano con interfono

**Comment by riddik14** [comment]
Avevi ragione, sotto blueprint ce ne stavano tre. Ora ne ho lasciata una e va bene. Grazie caiosweet 
![IMG_8303](https://github.com/caiosweet/Package-Notification-HUB-AppDaemon/assets/37450907/7dfc6070-e3d5-4d16-807c-b5d4e517dd13)

**Comment by riddik14** [comment]
Io ho configurato di nuovo la blueprint più volte, quindi se devo riconfigurare l’hub dovrò prima eliminare le automazioni altrimenti si aggiungono

**Comment by caiosweet** [comment]
> Io ho configurato di nuovo la blueprint più volte, quindi se devo riconfigurare l’hub dovrò prima eliminare le automazioni altrimenti si aggiungono

Beh, elimina tutte le automazioni  fatte con la blueprint in `Settings > Automations & Scenes > Automation`
Poi ti crei una sola automazione dalla blueprint  `Settings > Automations & Scenes > Blueprints`

In seguito, per qualsiasi aggiornamento della configurazione, **si**, dovrai editare la singola automazione creata  `Settings > Automations & Scenes > Automation > Centro Notifiche - Configurazione Avvio `(o come l'hai chiamata, ovviamente, se l'hai rinominata)

**Comment by riddik14** [comment]
Ok. Buono a sapersi il funzionamento soprattutto a seguito di aggiornamenti. Grazie ancora.
