### ISSUE TITLE
Problemi con AppDaemon 0.15.2

### ISSUE THREAD

**Issue by crystalmau** [caiosweet/Package-Notification-HUB-AppDaemon#45]
Con la versione 0.15.2 di AppDaemon
If you have this in your appdaemon.yaml file:
secrets: /config/secrets.yaml
You will need to adjust this to:
secrets: /homeassistant/secrets.yaml

e quindi

WARNING Notifier_Dispatch: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/notifier/notifier_dispatch.py", line 51, in initialize
    with open(secretsFile, "r") as ymlfile:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/config/packages/secrets.yaml'

**Comment by caiosweet** [comment]
Non dipende dal CN, ma dall'addon Appdaemon, segui questo:
[the appdaemon data folder will migrate](https://github.com/hassio-addons/addon-appdaemon/releases/tag/v0.15.0
)

Apri il file `/addon_configs/a0d7b954_appdaemon/appdaemon.yaml` , sostituisci `/config/secrets.yaml `con `/homeassistant/secrets.yaml`
riavvia appdaemon e ti funzionera' tutto, anche CN.

Probabilmente, se hai attivato i logs personalizzati, vanno cambiati anche quei percorsi.

**Comment by crystalmau** [comment]
Prima cosa grazie del supporto. Avevo già modificato quella parte come da breaking change.
Ho anche rifatto la configurazione di avvio inserendo homeassistant/package al posto di config/package

Per caso mi potresti mandare un esempio di come viene strutturato secrets.yaml in packages?

Grazie

**Comment by caiosweet** [comment]
Ciao, in teoria il secret non lo usiamo più, ma va tutto configurato tramite una semplice blueprint.
qui trovi tutto su come procedere con l'[Installazione](https://github.com/caiosweet/Package-Notification-HUB-AppDaemon/wiki#installation) con ultima versione 5.1.2. (Ci sono anche dei piccoli video in gif).

**Comment by crystalmau** [comment]
Ok grazie
