### ISSUE TITLE
Banned custom component used in lovelace

### ISSUE THREAD

**Issue by jokerigno** [caiosweet/Package-Notification-HUB-AppDaemon#6]
I don't know if you noticed that "button-entity-row"  has been banned from hacs for security issue. 

https://github.com/custom-cards/button-entity-row/issues/27

So maybe you want to remove it from your config...

Bye!

**Comment by caiosweet** [comment]
> I don't know if you noticed that "button-entity-row" has been banned from hacs for security issue.
> 
> [custom-cards/button-entity-row#27](https://github.com/custom-cards/button-entity-row/issues/27)
> 
> So maybe you want to remove it from your config...
> 
> Bye!


...maybe you haven't noticed that I already changed some time ago with the new and more performing [paper-buttons-row](https://github.com/jcwillox/lovelace-paper-buttons-row) 😇

See [new card](https://github.com/caiosweet/Package-Notification-HUB-AppDaemon/blob/1e344423c77254681b1b8f6c80ad5835e145dbcb/extra/my_lovelace_card_new.yaml#L23)

**Comment by jokerigno** [comment]
I missed that! Sorry for the disturb :)
